version: '3.9'

networks:
  app-net:
    driver: bridge

services:
  backend:
    build: .
    container_name: url-shortener
    ports:
      - "8080:8080"
    networks:
      - app-net
    depends_on:
      zookeeper1:
        condition: service_healthy
      zookeeper2:
        condition: service_healthy
      zookeeper3:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - ZOOKEEPER_URLS=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ZOOKEEPER_BASE_PATH=/url-shortener
      - REDIS_URL=${REDIS_URL}
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped

  zookeeper1:
    image: zookeeper:3.9.2
    container_name: zk1
    hostname: zookeeper1
    networks:
      - app-net
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181 | grep Mode"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - zk1-data:/data
      - zk1-log:/datalog
    restart: unless-stopped

  zookeeper2:
    image: zookeeper:3.9.2
    container_name: zk2
    hostname: zookeeper2
    networks:
      - app-net
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181 | grep Mode"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - zk2-data:/data
      - zk2-log:/datalog
    restart: unless-stopped

  zookeeper3:
    image: zookeeper:3.9.2
    container_name: zk3
    hostname: zookeeper3
    networks:
      - app-net
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181 | grep Mode"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - zk3-data:/data
      - zk3-log:/datalog
    restart: unless-stopped

volumes:
  zk1-data:
  zk1-log:
  zk2-data:
  zk2-log:
  zk3-data:
  zk3-log:
